service: notes-app

frameworkVersion: "3"

package:
  individually: true

custom:
  forceExclude:
    - "aws-sdk"

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs16.x
  stage: prod
  region: ap-southeast-1
  environment:
    tableName: notes
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "*"

functions:
  create:
    handler: create.main
    events:
      - http:
          path: /notes
          cors: true
          method: POST
          authorizer: aws_iam
  get:
    handler: get.main
    events:
      - http:
          path: /notes/{id}
          cors: true
          method: GET
          authorizer: aws_iam
  list:
    handler: list.main
    events:
      - http:
          path: /notes
          cors: true
          method: GET
          authorizer: aws_iam
  update:
    handler: update.main
    events:
      - http:
          path: /notes/{id}
          cors: true
          method: PUT
          authorizer: aws_iam
  delete:
    handler: delete.main
    events:
      - http:
          path: /notes/{id}
          cors: true
          method: DELETE
          authorizer: aws_iam
